<?php

class Tally
{
	public function sales_ledger()
	{
		$GUID = rand(1,10000);//'6593251k-803u-731g-953p-597825398422-I0000040';
		$ADDITIONALNAME = rand(1,10000);//'0010817840';
		$clientName = 'KRISHNANATH DHAS'; //client name
		$REFERENCE = 'Testing Inovice Number';//invoice number
		$EFFECTIVEDATE = '20221102'; // date
		$taxclassfication = 12;
		$BASIC = 30; // basic Amount
		$dolleramount = $BASIC*82;//amount calcultion for doller 
		$GST = $dolleramount * $taxclassfication/100; // Gst Amount
		$LANDING = $dolleramount - $GST; // Without GST Amount
		$paymentMode = 'Cash-in-hand'; // payment Mode
		$VOUCHER_NUMBER = 15; // Voucher Number
		
	$requestXML = '<?xml version="1.0"?>
		<ENVELOPE>
		<HEADER>
		<TALLYREQUEST>Import Data</TALLYREQUEST>
		</HEADER>
		<BODY>
		<IMPORTDATA>
		<REQUESTDESC>
		<REPORTNAME>All Masters</REPORTNAME>
		</REQUESTDESC>
		<REQUESTDATA>

		<!-- Create UNIT named "Nos" -->
		<TALLYMESSAGE xmlns:UDF="TallyUDF">
		 <UNIT NAME="Nos" ACTION="CREATE">
		  <NAME>Nos</NAME>
		  <ISSIMPLEUNIT>Yes</ISSIMPLEUNIT>
		  <FORPAYROLL>No</FORPAYROLL>
		 </UNIT>
		</TALLYMESSAGE>

		<!-- Create Stock Group named "Market Research Report Group" -->
		<TALLYMESSAGE xmlns:UDF="TallyUDF">
		<STOCKGROUP NAME="Market Research Report Group" ACTION="Create">
		<NAME.LIST>
		<NAME>Market Research Report Group</NAME>
		</NAME.LIST>
		<PARENT/>
		<ISADDABLE>Yes</ISADDABLE>
		</STOCKGROUP>
		</TALLYMESSAGE>

		<!-- Create Stock Item named "Market Research Report" -->
		<TALLYMESSAGE xmlns:UDF="TallyUDF">
		<STOCKITEM NAME="Market Research Report" ACTION="Create">
		<NAME.LIST>
			<NAME>Market Research Report</NAME>
		</NAME.LIST>
		<ADDITIONALNAME.LIST>
			<ADDITIONALNAME>'.$ADDITIONALNAME.'</ADDITIONALNAME>
		</ADDITIONALNAME.LIST>
		<PARENT>Market Research Report Group</PARENT>
		<BASEUNITS>NOS</BASEUNITS>
		<OPENINGBALANCE>0.000 NOS</OPENINGBALANCE>
		<OPENINGVALUE>0.000</OPENINGVALUE>
		<OPENINGRATE>0.000/NOS</OPENINGRATE>
		<BATCHALLOCATIONS.LIST>
			<NAME>Primary Batch</NAME>
			<BATCHNAME>Primary Batch</BATCHNAME>
			<GODOWNNAME>Main Location</GODOWNNAME>
			<MFDON>20070331</MFDON>
			<OPENINGBALANCE>0.000 NOS</OPENINGBALANCE>
			<OPENINGVALUE>0.000</OPENINGVALUE>
			<OPENINGRATE>0.000/NOS</OPENINGRATE>
		</BATCHALLOCATIONS.LIST>
		<STANDARDPRICELIST.LIST>
			<RATE>100.000</RATE>
			<DATE>20070401</DATE>
		</STANDARDPRICELIST.LIST>
		<STANDARDCOSTLIST.LIST>
			<RATE>80.000</RATE>
			<DATE>20070401</DATE>
		</STANDARDCOSTLIST.LIST>
		<REORDERBASE>0.000</REORDERBASE>
		<MINIMUMORDERBASE>0.000</MINIMUMORDERBASE>
		</STOCKITEM>
		</TALLYMESSAGE>

		<!-- Create Ledger named "Cash" if it does not exist -->
		<TALLYMESSAGE xmlns:UDF="TallyUDF">
		<LEDGER NAME="'.$clientName.'" ACTION="Create">
		<NAME.LIST>
		<NAME>'.$clientName.'</NAME>
		</NAME.LIST>
		<PARENT>'.$paymentMode.'</PARENT>
		<ISBILLWISEON>No</ISBILLWISEON>
		<AFFECTSSTOCK>No</AFFECTSSTOCK>
		<OPENINGBALANCE>0</OPENINGBALANCE>
		<USEFORVAT>No </USEFORVAT>
		<TAXCLASSIFICATIONNAME/>
		<TAXTYPE/>
		<RATEOFTAXCALCULATION/>
		</LEDGER>
		</TALLYMESSAGE>

		<!-- Create Ledger named "SALE OF Market Research Report Group @4% -->
		<TALLYMESSAGE xmlns:UDF="TallyUDF">
		<LEDGER NAME="SALE OF Market Research Report Group @'.$taxclassfication.'%" ACTION="Create">
		<NAME.LIST>
		<NAME>SALE OF Market Research Report Group @'.$taxclassfication.'%</NAME>
		</NAME.LIST>
		<PARENT>Sales Accounts</PARENT>
		<ISBILLWISEON>No</ISBILLWISEON>
		<AFFECTSSTOCK>Yes</AFFECTSSTOCK>
		<OPENINGBALANCE>0</OPENINGBALANCE>
		<USEFORVAT>Yes</USEFORVAT>
		<TAXCLASSIFICATIONNAME></TAXCLASSIFICATIONNAME>
		</LEDGER>
		</TALLYMESSAGE>

		<!-- Create Ledger named "GST Output @18%" -->
		<TALLYMESSAGE xmlns:UDF="TallyUDF">
		<LEDGER NAME="GST OUTPUT '.$taxclassfication.'%" ACTION="Create">
		<NAME.LIST>
		<NAME>GST OUTPUT '.$taxclassfication.'%</NAME>
		</NAME.LIST>
		<PARENT>Duties &amp; Taxes</PARENT>
		<ISBILLWISEON>No</ISBILLWISEON>
		<AFFECTSSTOCK>No</AFFECTSSTOCK>
		<OPENINGBALANCE>0</OPENINGBALANCE>
		<USEFORVAT>Yes</USEFORVAT>
		<TAXCLASSIFICATIONNAME></TAXCLASSIFICATIONNAME>
		<TAXTYPE>GST</TAXTYPE>
		<RATEOFTAXCALCULATION>'.$taxclassfication.'.00</RATEOFTAXCALCULATION>
		</LEDGER>
		</TALLYMESSAGE>

		<!-- Create Sales Voucher -->
		<TALLYMESSAGE xmlns:UDF="TallyUDF">
		<VOUCHER REMOTEID="'.$GUID.'" VCHTYPE="Sales">
		<ISOPTIONAL>No</ISOPTIONAL>
		<USEFORGAINLOSS>No</USEFORGAINLOSS>
		<USEFORCOMPOUND>No</USEFORCOMPOUND>
		<VOUCHERTYPENAME>Sales</VOUCHERTYPENAME>
		<VOUCHERNUMBER>'.$VOUCHER_NUMBER.'</VOUCHERNUMBER>

		<DATE>'.$EFFECTIVEDATE.'</DATE>
		<EFFECTIVEDATE>'.$EFFECTIVEDATE.'</EFFECTIVEDATE>
		<ISCANCELLED>No</ISCANCELLED>
		<USETRACKINGNUMBER>No</USETRACKINGNUMBER>
		<ISPOSTDATED>No</ISPOSTDATED>
		<ISINVOICE>Yes</ISINVOICE>
		<DIFFACTUALQTY>No</DIFFACTUALQTY>
		<ASPAYSLIP>No</ASPAYSLIP>
		<GUID>'.$GUID.'</GUID>
		<REFERENCE>'.$REFERENCE.'</REFERENCE>
		<PARTYLEDGERNAME>CASH</PARTYLEDGERNAME>
		<NARRATION/>
		<LEDGERENTRIES.LIST>
		<REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
		<ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
		<LEDGERFROMITEM>No</LEDGERFROMITEM>
		<LEDGERNAME>'.$clientName.'</LEDGERNAME>
		<AMOUNT>-'.$dolleramount.'</AMOUNT>
		</LEDGERENTRIES.LIST>
		<ALLINVENTORYENTRIES.LIST>
		<ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
		<STOCKITEMNAME>Market Research Report</STOCKITEMNAME>
		<AMOUNT>'.$LANDING.'</AMOUNT>
		<ACTUALQTY>1.000</ACTUALQTY>
		<BILLEDQTY>1.000</BILLEDQTY>
		<RATE>'.$LANDING.'</RATE>
		<ACCOUNTINGALLOCATIONS.LIST>
		<REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
		<ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
		<LEDGERFROMITEM>No</LEDGERFROMITEM>
		<TAXCLASSIFICATIONNAME/>
		<LEDGERNAME>SALE OF Market Research Report Group @'.$taxclassfication.'%</LEDGERNAME>
		<AMOUNT>'.$LANDING.'</AMOUNT>
		</ACCOUNTINGALLOCATIONS.LIST>
		<BATCHALLOCATIONS.LIST>
		<TRACKINGNUMBER/>
		<BATCHNAME>Primary Batch</BATCHNAME>
		<GODOWNNAME>Main Location</GODOWNNAME>
		<MFDON>20070401</MFDON>
		<EXPIRYPERIOD/>
		<AMOUNT>'.$LANDING.'</AMOUNT>
		<ACTUALQTY>1.000</ACTUALQTY>
		<BILLEDQTY>1.000</BILLEDQTY>
		<ORDERNO/>
		</BATCHALLOCATIONS.LIST>
		</ALLINVENTORYENTRIES.LIST>
		<LEDGERENTRIES.LIST>
		<REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
		<ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
		<LEDGERFROMITEM>No</LEDGERFROMITEM>
		<LEDGERNAME>GST OUTPUT '.$taxclassfication.'%</LEDGERNAME>
		<TAXCLASSIFICATIONNAME></TAXCLASSIFICATIONNAME>
		<UDF:RATEOFINVOICETAX.LIST DESC="`RATEOFINVOICETAX`" ISLIST="YES">
		<UDF:RATEOFINVOICETAX DESC="`RATEOFINVOICETAX`">'.$taxclassfication.'.000</UDF:RATEOFINVOICETAX>
		</UDF:RATEOFINVOICETAX.LIST>
		<AMOUNT>'.$GST.'</AMOUNT>
		<VATASSESSABLEVALUE>'.$LANDING.'</VATASSESSABLEVALUE>
		</LEDGERENTRIES.LIST>
		<INVOICEDELNOTES.LIST/>
		</VOUCHER>
		</TALLYMESSAGE>
		</REQUESTDATA>
		</IMPORTDATA>
		</BODY>
		</ENVELOPE>
	';

		//print_r($requestXML);
		/* Actual code for importing goes here */
		$server = 'http://localhost:9000';
		$headers = array("Content-type: text/xml", "Content-length: " . strlen($requestXML), "Connection: close");

		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, $server);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_TIMEOUT, 100);
		curl_setopt($ch, CURLOPT_POST, true);
		curl_setopt($ch, CURLOPT_POSTFIELDS, $requestXML);
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
		$data = curl_exec($ch);

		if (curl_errno($ch)) {
			print curl_error($ch);
			echo "  something went wrong..... try again later";
		} else {
			echo "request accepted";
			print $data;
			curl_close($ch);
		}
	}
}
	$obj = new Tally();	
	echo $obj->sales_ledger();

?>